spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: ddangme
    password: qwerty123456

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.sql: debug